apiVersion: v1
kind: Namespace
metadata:
  name: lab-dpb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-test-dpb
  namespace: lab-dpb
  labels:
    app: backend-nest-test-dpb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-test-dpb
  template:
    metadata:
      labels:
        app: backend-nest-test-dpb
    spec:
      containers:
      - name: backend-nest-test-dpb
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-test-dpb
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred-backend-nest-test-dpb
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nest-test-dpb-svc
  namespace: lab-dpb
  labels:
    app: backend-nest-test-dpb-svc
spec:
  selector:
     app: backend-nest-test-dpb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4066
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend-nest-test-dpb
  namespace: lab-dpb
spec:
  ingressClassName: nginx
  rules:
  - host: dpb.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-nest-test-dpb-svc
            port:
              number: 80